language: node_js
node_js: 14

cache:
  directories:
  - node_modules

before install:
  - git fetch origin

install:
  - npm i -g npm@6.14.13
  - npm --version
  - npm i

script:
  - npm run lint
  - npm set audit-level high
  - npm config set audit-level high
  - npm audit
  - npm run build
  - npm run test
